import { useState, useMemo } from 'react';
import { Search, Plus, ChevronDown, ChevronUp, FileDown, Link2, Loader2 } from 'lucide-react';
import { AnimatePresence, motion } from 'motion/react';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { useLang } from '@/i18n';
import { useWorkspaces, useInvoices, useRetainers, useClients, useAddRetainer } from '@/lib/hooks/useSupabase';
import { Sheet, SheetContent, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { toast } from 'sonner';
import { supabase } from '@/lib/supabase';

function printInvoice(invoice: any, client: any, lang: string) {
  const locale = lang === 'fr' ? 'fr-FR' : 'en-US';
  const fmtCurrency = (n: number) =>
    new Intl.NumberFormat(locale, { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n);

  const rows = (invoice.items ?? []).map((item: any) => `
    <tr>
      <td>${item.description}</td>
      <td style="text-align:center">${item.quantity}</td>
      <td style="text-align:right">${fmtCurrency(item.price)}</td>
      <td style="text-align:right">${fmtCurrency(item.quantity * item.price)}</td>
    </tr>`).join('');

  const html = `<!DOCTYPE html><html><head><title>${invoice.invoiceNumber}</title>
  <style>
    body{font-family:Inter,system-ui,sans-serif;color:#111;padding:48px;max-width:780px;margin:0 auto}
    h1{font-size:28px;margin-bottom:4px}
    .meta{color:#555;font-size:13px;margin-bottom:32px}
    table{width:100%;border-collapse:collapse;margin-top:24px}
    th{border-bottom:2px solid #111;padding:8px 4px;text-align:left;font-size:12px;text-transform:uppercase;letter-spacing:.05em}
    td{padding:8px 4px;font-size:13px;border-bottom:1px solid #eee}
    .total-row td{font-weight:600;border-top:2px solid #111;border-bottom:none}
    .footer{margin-top:48px;font-size:12px;color:#777}
    @media print{body{padding:0}}
  </style></head><body>
  <h1>${invoice.invoiceNumber}</h1>
  <div class="meta">
    <div><strong>${client?.company ?? ''}</strong></div>
    <div>Date: ${new Date(invoice.date).toLocaleDateString(locale)}</div>
    <div>Due: ${new Date(invoice.dueDate).toLocaleDateString(locale)}</div>
    <div>Status: ${invoice.status}</div>
  </div>
  <table>
    <thead><tr><th>Description</th><th style="text-align:center">Qty</th><th style="text-align:right">Unit price</th><th style="text-align:right">Total</th></tr></thead>
    <tbody>${rows}</tbody>
    <tfoot><tr class="total-row"><td colspan="3" style="text-align:right">Total</td><td style="text-align:right">${fmtCurrency(invoice.amount)}</td></tr></tfoot>
  </table>
  <div class="footer">Generated by Minerva OS · Uprising Studio</div>
  <script>window.onload=()=>{window.print();}</script>
  </body></html>`;

  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(html);
  win.document.close();
}


function fmt(n: number, lang: string) {
  return new Intl.NumberFormat(lang === 'fr' ? 'fr-FR' : 'en-US', { 
    style: 'currency', 
    currency: 'USD', 
    maximumFractionDigits: 0 
  }).format(n);
}

function InvoiceRow({ invoice, t, lang, clients }: { invoice: any; t: any; lang: string, clients: any[] }) {
  const [expanded, setExpanded] = useState(false);
  const [generatingLink, setGeneratingLink] = useState(false);
  const [linkFeedback, setLinkFeedback] = useState<'copied' | 'error' | null>(null);
  const b = t.app.billing;
  const common = t.app.common;
  
  const client = clients.find((c: any) => c._id === invoice.clientId);

  async function handlePaymentLink() {
    setGeneratingLink(true);
    setLinkFeedback(null);
    try {
      const res = await fetch('/api/stripe/checkout', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          invoiceId: invoice._id,
          amount: invoice.amount,
          currency: 'USD',
          clientEmail: client?.email ?? '',
        }),
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      await navigator.clipboard.writeText(data.url);
      setLinkFeedback('copied');
      setTimeout(() => setLinkFeedback(null), 2500);
    } catch {
      setLinkFeedback('error');
      setTimeout(() => setLinkFeedback(null), 2500);
    } finally {
      setGeneratingLink(false);
    }
  }

  const STATUS_CONFIG: Record<string, { label: string; class: string }> = {
    draft:     { label: common.status.draft,     class: 'text-fog bg-fog/10 border-fog/20'       },
    sent:      { label: common.status.pending,   class: 'text-warm bg-warm/10 border-warm/20'    },
    overdue:   { label: common.status.overdue,   class: 'text-ember bg-ember/10 border-ember/20' },
    paid:      { label: common.status.paid,      class: 'text-sage bg-sage/10 border-sage/20'    },
    cancelled: { label: common.status.rejected, class: 'text-fog bg-fog/5 border-fog/15'        },
  };

  const sc = STATUS_CONFIG[invoice.status] || STATUS_CONFIG.draft;

  return (
    <div
      className="rounded-xl border overflow-hidden transition-colors duration-200"
      style={{ backgroundColor: 'rgba(255,255,255,0.02)', borderColor: 'rgba(255,255,255,0.06)' }}
    >
      <div
        className="flex items-center gap-4 px-4 py-3 cursor-pointer hover:bg-white/[0.015]"
        onClick={() => setExpanded(e => !e)}
      >
        {/* Number */}
        <div className="w-32 shrink-0">
          <p className="text-sm font-semibold text-ivory tabular-nums">{invoice.invoiceNumber}</p>
        </div>

        {/* Client + project */}
        <div className="flex-1 min-w-0">
          <p className="text-sm text-ivory truncate">{client?.company || '...'}</p>
        </div>

        {/* Status */}
        <span className={cn('text-[10px] font-medium px-2 py-0.5 rounded-full border shrink-0', sc.class)}>
          {sc.label}
        </span>

        {/* Dates */}
        <div className="hidden md:block text-right shrink-0">
          <p className="text-xs text-fog">
            {invoice.status === 'paid'
              ? `${b.invoices.paid} ${new Date(invoice.date).toLocaleDateString(lang === 'fr' ? 'fr-FR' : 'en-GB', { day: 'numeric', month: 'short' })}`
              : `${b.invoices.due} ${new Date(invoice.dueDate).toLocaleDateString(lang === 'fr' ? 'fr-FR' : 'en-GB', { day: 'numeric', month: 'short' })}`}
          </p>
        </div>

        {/* Amount */}
        <p className="text-sm font-semibold text-ivory tabular-nums shrink-0 w-20 text-right">
          {fmt(invoice.amount, lang)}
        </p>

        {/* Expand toggle */}
        <div className="text-fog shrink-0">
          {expanded ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
        </div>
      </div>

      {/* Line items */}
      <AnimatePresence>
        {expanded && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25, ease: [0.22, 1, 0.36, 1] }}
            className="overflow-hidden"
          >
            <div className="px-4 pb-3 pt-1" style={{ borderTop: '1px solid rgba(255,255,255,0.05)' }}>
              <table className="w-full text-xs">
                <thead>
                  <tr className="text-fog uppercase tracking-wider">
                    <th className="text-left py-1.5 font-medium">{b.table.description}</th>
                    <th className="text-right py-1.5 font-medium w-12">{b.table.qty}</th>
                    <th className="text-right py-1.5 font-medium w-24">{b.table.unitPrice}</th>
                    <th className="text-right py-1.5 font-medium w-24">{b.table.total}</th>
                  </tr>
                </thead>
                <tbody>
                  {invoice.items.map((item: any, i: number) => (
                    <tr key={i} className="border-t" style={{ borderColor: 'rgba(255,255,255,0.04)' }}>
                      <td className="py-1.5 text-silver">{item.description}</td>
                      <td className="py-1.5 text-right text-fog tabular-nums">{item.quantity}</td>
                      <td className="py-1.5 text-right text-fog tabular-nums">{fmt(item.price, lang)}</td>
                      <td className="py-1.5 text-right text-silver tabular-nums font-medium">{fmt(item.quantity * item.price, lang)}</td>
                    </tr>
                  ))}
                </tbody>
                <tfoot>
                  <tr style={{ borderTop: '1px solid rgba(255,255,255,0.08)' }}>
                    <td colSpan={3} className="pt-2 text-right text-fog font-medium">Total</td>
                    <td className="pt-2 text-right text-ivory font-semibold tabular-nums">{fmt(invoice.amount, lang)}</td>
                  </tr>
                </tfoot>
              </table>

              {/* Invoice actions */}
              <div className="flex items-center gap-2 mt-3 pt-3" style={{ borderTop: '1px solid rgba(255,255,255,0.05)' }}>
                <button
                  onClick={() => printInvoice(invoice, client, lang)}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs text-fog hover:text-ivory transition-colors hover:bg-white/5"
                >
                  <FileDown size={12} />
                  {b.actions.exportPdf}
                </button>
                {invoice.status !== 'paid' && (
                  <button
                    onClick={handlePaymentLink}
                    disabled={generatingLink}
                    className={cn(
                      'flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs transition-colors',
                      linkFeedback === 'copied'
                        ? 'text-sage bg-sage/10'
                        : linkFeedback === 'error'
                          ? 'text-ember bg-ember/10'
                          : 'text-fog hover:text-ivory hover:bg-white/5'
                    )}
                  >
                    {generatingLink
                      ? <Loader2 size={12} className="animate-spin" />
                      : <Link2 size={12} />}
                    {linkFeedback === 'copied'
                      ? b.actions.paymentLinkCopied
                      : linkFeedback === 'error'
                        ? b.actions.paymentLinkError
                        : generatingLink
                          ? b.actions.generating
                          : b.actions.paymentLink}
                  </button>
                )}
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export default function Billing() {
  const { t, lang } = useLang();
  const b = t.app.billing;

  const workspaces = useWorkspaces();
  const workspaceId = workspaces[0]?.id;

  const invoices = useInvoices(workspaceId);
  const retainers = useRetainers(workspaceId);
  const clients = useClients(workspaceId);

  const [filter, setFilter] = useState<string | 'all'>('all');
  const [query, setQuery]   = useState('');
  const [retainerSheetOpen, setRetainerSheetOpen] = useState(false);
  const [invoiceSheetOpen, setInvoiceSheetOpen] = useState(false);
  const [newInvoiceForm, setNewInvoiceForm] = useState({
    clientId: '',
    amount: '',
    dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    invoiceNumber: `INV-${Date.now().toString().slice(-6)}`,
    description: '',
  });
  const [addingInvoice, setAddingInvoice] = useState(false);
  const [newRetainerForm, setNewRetainerForm] = useState({
    clientId: '',
    amount: '',
    cycle: 'monthly',
    hoursIncluded: '',
    startDate: new Date().toISOString().split('T')[0],
    notes: '',
  });

  const addRetainer = useAddRetainer();

  async function handleAddInvoice() {
    if (!newInvoiceForm.clientId || !newInvoiceForm.amount) {
      toast.error(lang === 'fr' ? 'Veuillez remplir tous les champs obligatoires' : 'Please fill all required fields');
      return;
    }
    setAddingInvoice(true);
    try {
      const { error } = await supabase
        .from('invoices')
        .insert({
          workspace_id: workspaceId,
          client_id: newInvoiceForm.clientId,
          invoice_number: newInvoiceForm.invoiceNumber,
          amount: parseFloat(newInvoiceForm.amount),
          status: 'draft',
          date: new Date().toISOString().split('T')[0],
          due_date: newInvoiceForm.dueDate,
          items: newInvoiceForm.description ? [{ description: newInvoiceForm.description, quantity: 1, price: parseFloat(newInvoiceForm.amount) }] : [],
        });
      if (error) throw error;
      toast.success(lang === 'fr' ? 'Facture créée avec succès' : 'Invoice created successfully');
      setInvoiceSheetOpen(false);
      setNewInvoiceForm({
        clientId: '',
        amount: '',
        dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        invoiceNumber: `INV-${Date.now().toString().slice(-6)}`,
        description: '',
      });
    } catch (e) {
      console.error(e);
      toast.error(lang === 'fr' ? "Erreur lors de la création de la facture" : "Failed to create invoice");
    } finally {
      setAddingInvoice(false);
    }
  }

  async function handleAddRetainer() {
    if (!newRetainerForm.clientId || !newRetainerForm.amount || !newRetainerForm.hoursIncluded) {
      toast.error(lang === 'fr' ? 'Veuillez remplir tous les champs obligatoires' : 'Please fill all required fields');
      return;
    }
    try {
      const start = new Date(newRetainerForm.startDate);
      if (newRetainerForm.cycle === 'monthly') {
        start.setMonth(start.getMonth() + 1);
      } else if (newRetainerForm.cycle === 'quarterly') {
        start.setMonth(start.getMonth() + 3);
      } else if (newRetainerForm.cycle === 'annual') {
        start.setFullYear(start.getFullYear() + 1);
      }
      const renewalDate = start.toISOString().split('T')[0];

      await addRetainer({
        workspaceId,
        clientId: newRetainerForm.clientId,
        amount: parseFloat(newRetainerForm.amount),
        cycle: newRetainerForm.cycle,
        status: 'active',
        startDate: newRetainerForm.startDate,
        renewalDate,
        hoursIncluded: parseFloat(newRetainerForm.hoursIncluded),
        hoursUsed: 0,
        notes: newRetainerForm.notes || undefined,
      });
      toast.success(lang === 'fr' ? 'Forfait ajouté avec succès' : 'Retainer added successfully');
      setRetainerSheetOpen(false);
      setNewRetainerForm({
        clientId: '',
        amount: '',
        cycle: 'monthly',
        hoursIncluded: '',
        startDate: new Date().toISOString().split('T')[0],
        notes: '',
      });
    } catch (e) {
      console.error(e);
      toast.error(lang === 'fr' ? "Erreur lors de la création du forfait" : "Failed to create retainer");
    }
  }

  const FILTER_TABS = useMemo(() => [
    { id: 'all' as const,     label: t.app.tasks.filters.all },
    { id: 'sent' as const,    label: t.app.common.status.pending },
    { id: 'overdue' as const, label: t.app.common.status.overdue },
    { id: 'draft' as const,   label: t.app.common.status.draft },
    { id: 'paid' as const,    label: t.app.common.status.paid },
  ], [t]);

  const outstanding = invoices.filter((i: any) => i.status === 'sent' || i.status === 'overdue').reduce((s: any, i: any) => s + i.amount, 0);
  const paidMTD     = invoices.filter((i: any) => i.status === 'paid').reduce((s: any, i: any) => s + i.amount, 0);
  const overdueCount = invoices.filter((i: any) => i.status === 'overdue').length;

  const visible = invoices.filter((i: any) => {
    const matchFilter = filter === 'all' || i.status === filter;
    const matchQuery  = query === '' ||
      i.invoiceNumber.toLowerCase().includes(query.toLowerCase());
    return matchFilter && matchQuery;
  });

  return (
    <>
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-semibold text-ivory">{b.title}</h1>
          <p className="text-sm text-fog mt-0.5">
            {b.stats
              .replace('invoices', String(invoices.length))
              .replace('active retainers', String(retainers.filter((r: any) => r.status === 'active').length))}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button size="sm" variant="outline" onClick={() => setRetainerSheetOpen(true)}>
            <Plus size={14} />
            {b.retainers.newRetainer}
          </Button>
          <Button size="sm" onClick={() => setInvoiceSheetOpen(true)}>
            <Plus size={14} />
            {b.newInvoice}
          </Button>
        </div>
      </div>

      {/* Summary strip */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8">
        {[
          { label: b.summary.outstanding,   value: fmt(outstanding, lang), color: outstanding > 0 ? 'text-warm'  : 'text-sage', sub: b.summary.outstandingSub },
          { label: b.summary.overdue,       value: String(overdueCount),  color: overdueCount > 0      ? 'text-ember' : 'text-sage', sub: overdueCount > 0 ? b.summary.overdueSub : b.summary.overdueNone },
          { label: b.summary.collected,     value: fmt(paidMTD, lang),     color: 'text-sage',   sub: b.summary.collectedSub },
        ].map((s: any) => (
          <div key={s.label} className="bg-card border border-border rounded-xl p-4">
            <p className={cn('text-2xl font-semibold tabular-nums', s.color)}>{s.value}</p>
            <p className="text-xs text-fog mt-1">{s.label}</p>
            <p className="text-[10px] text-fog/60 mt-0.5">{s.sub}</p>
          </div>
        ))}
      </div>

      {/* Retainers */}
      <section className="mb-8">
        <h2 className="text-sm font-semibold text-ivory mb-3">{b.retainers.title}</h2>
        {retainers.filter((r: any) => r.status === 'active').length === 0 ? (
          <p className="text-sm text-fog py-4">{b.retainers.empty}</p>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {retainers.filter((r: any) => r.status === 'active').map((ret: any) => {
              const client = clients.find((c: any) => c._id === ret.clientId);
              const pct = ret.hoursIncluded > 0 ? Math.round((ret.hoursUsed / ret.hoursIncluded) * 100) : 0;
              const barColor = pct >= 100 ? '#A86A6A' : pct >= 80 ? '#B89B6A' : '#7FA38A';
              return (
                <div key={ret._id} className="rounded-xl border border-border bg-card p-4">
                  <div className="flex items-start justify-between mb-3">
                    <div>
                      <p className="text-sm font-medium text-ivory">{client?.company || '...'}</p>
                      <p className="text-[10px] text-fog capitalize">
                        {ret.cycle} · {b.retainers.renews} {new Date(ret.renewalDate).toLocaleDateString(lang === 'fr' ? 'fr-FR' : 'en-GB', { day: 'numeric', month: 'short' })}
                      </p>
                    </div>
                    <p className="text-sm font-semibold text-ivory tabular-nums">{fmt(ret.amount, lang)}</p>
                  </div>
                  {/* Hours bar */}
                  <div>
                    <div className="flex justify-between text-[10px] text-fog mb-1">
                      <span>{b.retainers.hours}</span>
                      <span>{ret.hoursUsed} / {ret.hoursIncluded}h</span>
                    </div>
                    <div className="w-full h-1 rounded-full overflow-hidden bg-dusk">
                      <div
                        className="h-full rounded-full transition-all duration-500"
                        style={{ width: `${Math.min(pct, 100)}%`, backgroundColor: barColor }}
                      />
                    </div>
                  </div>
                  {ret.notes && <p className="text-[11px] text-fog/60 mt-2 leading-relaxed">{ret.notes}</p>}
                </div>
              );
            })}
          </div>
        )}
      </section>

      {/* Invoices */}
      <section>
        <div className="flex items-center gap-3 mb-4 flex-wrap">
          {/* Filters */}
          <div className="flex items-center gap-1 p-1 rounded-lg bg-card border border-border w-fit">
            {FILTER_TABS.map(tab => (
              <button
                key={tab.id}
                onClick={() => setFilter(tab.id)}
                className={cn(
                  'px-3 py-1.5 rounded-md text-xs font-medium transition-colors',
                  filter === tab.id ? 'bg-dusk text-ivory' : 'text-fog hover:text-silver'
                )}
              >
                {tab.label}
              </button>
            ))}
          </div>

          {/* Search */}
          <div className="relative">
            <Search size={13} className="absolute left-3 top-1/2 -translate-y-1/2 text-fog pointer-events-none" />
            <input
              type="text"
              placeholder={b.invoices.searchPlaceholder}
              value={query}
              onChange={e => setQuery(e.target.value)}
              className="pl-8 pr-3 py-1.5 rounded-lg text-xs text-ivory placeholder:text-fog outline-none transition-colors"
              style={{
                backgroundColor: 'rgba(255,255,255,0.04)',
                border: '1px solid rgba(255,255,255,0.08)',
                fontFamily: "'Inter', sans-serif",
              }}
            />
          </div>
        </div>

        <div className="space-y-2">
          {visible.length === 0 && (
            <p className="text-sm text-fog text-center py-10">{b.invoices.empty}</p>
          )}
          {visible.map((inv: any) => <InvoiceRow key={inv._id} invoice={inv} t={t} lang={lang} clients={clients} />)}
        </div>
      </section>

      {/* Add Invoice Sheet */}
      <Sheet open={invoiceSheetOpen} onOpenChange={setInvoiceSheetOpen}>
        <SheetContent side="right" className="w-96 p-6 flex flex-col gap-6">
          <SheetHeader>
            <SheetTitle>{b.newInvoice}</SheetTitle>
          </SheetHeader>
          <div className="flex flex-col gap-4 flex-1">
            <div className="space-y-1.5">
              <Label>{lang === 'fr' ? 'Numéro de facture' : 'Invoice number'}</Label>
              <Input
                value={newInvoiceForm.invoiceNumber}
                onChange={e => setNewInvoiceForm(f => ({ ...f, invoiceNumber: e.target.value }))}
              />
            </div>
            <div className="space-y-1.5">
              <Label>Client</Label>
              <Select
                value={newInvoiceForm.clientId}
                onValueChange={v => setNewInvoiceForm(f => ({ ...f, clientId: v }))}
              >
                <SelectTrigger>
                  <SelectValue placeholder={lang === 'fr' ? 'Sélectionner un client' : 'Select a client'} />
                </SelectTrigger>
                <SelectContent>
                  {clients.map((c: any) => (
                    <SelectItem key={c._id} value={c._id}>{c.company}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <Label>{lang === 'fr' ? 'Montant (USD)' : 'Amount (USD)'}</Label>
              <Input
                type="number"
                placeholder="5000"
                value={newInvoiceForm.amount}
                onChange={e => setNewInvoiceForm(f => ({ ...f, amount: e.target.value }))}
              />
            </div>
            <div className="space-y-1.5">
              <Label>{lang === 'fr' ? 'Description (optionnel)' : 'Description (optional)'}</Label>
              <Input
                placeholder={lang === 'fr' ? 'Services de design web...' : 'Web design services...'}
                value={newInvoiceForm.description}
                onChange={e => setNewInvoiceForm(f => ({ ...f, description: e.target.value }))}
              />
            </div>
            <div className="space-y-1.5">
              <Label>{lang === 'fr' ? "Date d'échéance" : 'Due date'}</Label>
              <Input
                type="date"
                value={newInvoiceForm.dueDate}
                onChange={e => setNewInvoiceForm(f => ({ ...f, dueDate: e.target.value }))}
              />
            </div>
          </div>
          <Button className="w-full" onClick={handleAddInvoice} disabled={addingInvoice}>
            {addingInvoice ? <><Loader2 size={14} className="animate-spin mr-2" />{lang === 'fr' ? 'Création...' : 'Creating...'}</> : lang === 'fr' ? 'Créer la facture' : 'Create Invoice'}
          </Button>
        </SheetContent>
      </Sheet>

      {/* Add Retainer Sheet */}
      <Sheet open={retainerSheetOpen} onOpenChange={setRetainerSheetOpen}>
        <SheetContent side="right" className="w-96 p-6 flex flex-col gap-6">
          <SheetHeader>
            <SheetTitle>{b.retainers.newRetainer}</SheetTitle>
          </SheetHeader>

          <div className="flex flex-col gap-4 flex-1">
            <div className="space-y-1.5">
              <Label>Client</Label>
              <Select
                value={newRetainerForm.clientId}
                onValueChange={v => setNewRetainerForm(f => ({ ...f, clientId: v }))}
              >
                <SelectTrigger>
                  <SelectValue placeholder={lang === 'fr' ? 'Sélectionner un client' : 'Select a client'} />
                </SelectTrigger>
                <SelectContent>
                  {clients.map((c: any) => (
                    <SelectItem key={c._id} value={c._id}>
                      {c.company}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-1.5">
              <Label>{lang === 'fr' ? 'Montant (USD)' : 'Amount (USD)'}</Label>
              <Input
                type="number"
                placeholder="3000"
                value={newRetainerForm.amount}
                onChange={e => setNewRetainerForm(f => ({ ...f, amount: e.target.value }))}
              />
            </div>

            <div className="space-y-1.5">
              <Label>{b.retainers.cycle}</Label>
              <Select
                value={newRetainerForm.cycle}
                onValueChange={v => setNewRetainerForm(f => ({ ...f, cycle: v }))}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="monthly">{lang === 'fr' ? 'Mensuel' : 'Monthly'}</SelectItem>
                  <SelectItem value="quarterly">{lang === 'fr' ? 'Trimestriel' : 'Quarterly'}</SelectItem>
                  <SelectItem value="annual">{lang === 'fr' ? 'Annuel' : 'Annual'}</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-1.5">
              <Label>{b.retainers.hoursIncluded}</Label>
              <Input
                type="number"
                placeholder="20"
                value={newRetainerForm.hoursIncluded}
                onChange={e => setNewRetainerForm(f => ({ ...f, hoursIncluded: e.target.value }))}
              />
            </div>

            <div className="space-y-1.5">
              <Label>{lang === 'fr' ? 'Date de début' : 'Start Date'}</Label>
              <Input
                type="date"
                value={newRetainerForm.startDate}
                onChange={e => setNewRetainerForm(f => ({ ...f, startDate: e.target.value }))}
              />
            </div>

            <div className="space-y-1.5">
              <Label>{lang === 'fr' ? 'Notes (optionnel)' : 'Notes (optional)'}</Label>
              <Input
                placeholder="..."
                value={newRetainerForm.notes}
                onChange={e => setNewRetainerForm(f => ({ ...f, notes: e.target.value }))}
              />
            </div>
          </div>

          <Button className="w-full" onClick={handleAddRetainer}>
            {lang === 'fr' ? 'Créer le forfait' : 'Create Retainer'}
          </Button>
        </SheetContent>
      </Sheet>
    </>
  );
}

