"use client";
import { useState, useMemo } from 'react';
import { Search, Plus, ChevronDown, ChevronUp, FileDown, Link2, Loader2 } from 'lucide-react';
import { Skeleton } from '@/components/ui/skeleton';
import { AnimatePresence, motion } from 'motion/react';
import { AnimatedNumber } from '@/components/ui/animated-number';
import { TextAnimate } from '@/components/ui/text-animate';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { useLang } from '@/i18n';
import { useWorkspaces, useInvoices, useRetainers, useClients, useAddRetainer, useAddInvoice } from '@/lib/hooks/useSupabase';
import { Sheet, SheetContent, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { toast } from 'sonner';

function printInvoice(invoice: any, client: any, lang: string) {
  const locale = lang === 'fr' ? 'fr-FR' : 'en-US';
  const fmtCurrency = (n: number) =>
    new Intl.NumberFormat(locale, { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n);

  const rows = (invoice.items ?? []).map((item: any) => `
    <tr>
      <td>${item.description}</td>
      <td style="text-align:center">${item.quantity}</td>
      <td style="text-align:right">${fmtCurrency(item.price)}</td>
      <td style="text-align:right">${fmtCurrency(item.quantity * item.price)}</td>
    </tr>`).join('');

  const html = `<!DOCTYPE html><html><head><title>${invoice.invoiceNumber}</title>
  <style>
    body{font-family:Inter,system-ui,sans-serif;background-color:#FFFFFF;color:#0F172A;padding:48px;max-width:780px;margin:0 auto}
    h1{font-size:28px;margin-bottom:4px}
    .meta{color:#374151;font-size:13px;margin-bottom:32px}
    table{width:100%;border-collapse:collapse;margin-top:24px}
    th{border-bottom:2px solid #0F172A;padding:8px 4px;text-align:left;font-size:12px;text-transform:uppercase;letter-spacing:.05em}
    td{padding:8px 4px;font-size:13px;border-bottom:1px solid #E5E7EB}
    .total-row td{font-weight:600;border-top:2px solid #0F172A;border-bottom:none}
    .footer{margin-top:48px;font-size:12px;color:#6B7280}
    @media print{body{padding:0}}
  </style></head><body>
  <h1>${invoice.invoiceNumber}</h1>
  <div class="meta">
    <div><strong>${client?.company ?? ''}</strong></div>
    <div>Date: ${new Date(invoice.date).toLocaleDateString(locale)}</div>
    <div>Due: ${new Date(invoice.dueDate).toLocaleDateString(locale)}</div>
    <div>Status: ${invoice.status}</div>
  </div>
  <table>
    <thead><tr><th>Description</th><th style="text-align:center">Qty</th><th style="text-align:right">Unit price</th><th style="text-align:right">Total</th></tr></thead>
    <tbody>${rows}</tbody>
    <tfoot><tr class="total-row"><td colspan="3" style="text-align:right">Total</td><td style="text-align:right">${fmtCurrency(invoice.amount)}</td></tr></tfoot>
  </table>
  <div class="footer">Generated by Minerva OS · Uprising Studio</div>
  <script>window.onload=()=>{window.print();}</script>
  </body></html>`;

  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(html);
  win.document.close();
}


function fmt(n: number, lang: string) {
  return new Intl.NumberFormat(lang === 'fr' ? 'fr-FR' : 'en-US', { 
    style: 'currency', 
    currency: 'USD', 
    maximumFractionDigits: 0 
  }).format(n);
}

function InvoiceRow({ invoice, t, lang, clients }: { invoice: any; t: any; lang: string, clients: any[] }) {
  const [expanded, setExpanded] = useState(false);
  const [generatingLink, setGeneratingLink] = useState(false);
  const [linkFeedback, setLinkFeedback] = useState<'copied' | 'error' | null>(null);
  const b = t.app.billing;
  const common = t.app.common;
  
  const client = clients.find((c: any) => c._id === invoice.clientId);

  async function handlePaymentLink() {
    setGeneratingLink(true);
    setLinkFeedback(null);
    try {
      const res = await fetch('/api/stripe/checkout', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          invoiceId: invoice._id,
          amount: invoice.amount,
          currency: 'USD',
          clientEmail: client?.email ?? '',
        }),
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      await navigator.clipboard.writeText(data.url);
      setLinkFeedback('copied');
      setTimeout(() => setLinkFeedback(null), 2500);
    } catch {
      setLinkFeedback('error');
      setTimeout(() => setLinkFeedback(null), 2500);
    } finally {
      setGeneratingLink(false);
    }
  }

  const STATUS_CONFIG: Record<string, { label: string; class: string }> = {
    draft:     { label: common.status.draft,     class: 'text-fog bg-fog/10 border-fog/20'       },
    sent:      { label: common.status.pending,   class: 'text-warm bg-warm/10 border-warm/20'    },
    overdue:   { label: common.status.overdue,   class: 'text-ember bg-ember/10 border-ember/20' },
    paid:      { label: common.status.paid,      class: 'text-sage bg-sage/10 border-sage/20'    },
    cancelled: { label: common.status.rejected, class: 'text-fog bg-fog/5 border-fog/15'        },
  };

  const sc = STATUS_CONFIG[invoice.status] || STATUS_CONFIG.draft;

  return (
    <div
      className="rounded-xl border overflow-hidden transition-colors duration-200 bg-secondary/60 border-border"
    >
      <div
        className="flex items-center gap-3 px-4 py-3 cursor-pointer hover:bg-accent"
        onClick={() => setExpanded(e => !e)}
      >
        {/* Number */}
        <div className="w-24 sm:w-32 shrink-0">
          <p className="text-sm font-semibold text-ivory tabular-nums">{invoice.invoiceNumber}</p>
        </div>

        {/* Client + project */}
        <div className="flex-1 min-w-0">
          <p className="text-sm text-ivory truncate">{client?.company || '...'}</p>
        </div>

        {/* Status */}
        <span className={cn('text-[10px] font-medium px-2 py-0.5 rounded-full border shrink-0', sc.class)}>
          {sc.label}
        </span>

        {/* Dates */}
        <div className="hidden md:block text-right shrink-0">
          <p className="text-xs text-fog">
            {invoice.status === 'paid'
              ? `${b.invoices.paid} ${new Date(invoice.date).toLocaleDateString(lang === 'fr' ? 'fr-FR' : 'en-GB', { day: 'numeric', month: 'short' })}`
              : `${b.invoices.due} ${new Date(invoice.dueDate).toLocaleDateString(lang === 'fr' ? 'fr-FR' : 'en-GB', { day: 'numeric', month: 'short' })}`}
          </p>
        </div>

        {/* Amount */}
        <p className="text-sm font-semibold text-ivory tabular-nums shrink-0 w-20 text-right">
          {fmt(invoice.amount, lang)}
        </p>

        {/* Expand toggle */}
        <div className="text-fog shrink-0">
          {expanded ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
        </div>
      </div>

      {/* Line items */}
      <AnimatePresence>
        {expanded && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25, ease: [0.22, 1, 0.36, 1] }}
            className="overflow-hidden"
          >
            <div className="px-4 pb-3 pt-1 border-t border-border">
              <div className="overflow-x-auto">
              <table className="w-full text-xs">
                <thead>
                  <tr className="text-fog uppercase tracking-wider">
                    <th className="text-left py-1.5 font-medium">{b.table.description}</th>
                    <th className="text-right py-1.5 font-medium w-12">{b.table.qty}</th>
                    <th className="text-right py-1.5 font-medium w-24">{b.table.unitPrice}</th>
                    <th className="text-right py-1.5 font-medium w-24">{b.table.total}</th>
                  </tr>
                </thead>
                <tbody>
                  {invoice.items.map((item: any, i: number) => (
                    <tr key={i} className="border-t border-border">
                      <td className="py-1.5 text-silver">{item.description}</td>
                      <td className="py-1.5 text-right text-fog tabular-nums">{item.quantity}</td>
                      <td className="py-1.5 text-right text-fog tabular-nums">{fmt(item.price, lang)}</td>
                      <td className="py-1.5 text-right text-silver tabular-nums font-medium">{fmt(item.quantity * item.price, lang)}</td>
                    </tr>
                  ))}
                </tbody>
                <tfoot>
                  <tr className="border-t border-border">
                    <td colSpan={3} className="pt-2 text-right text-fog font-medium">Total</td>
                    <td className="pt-2 text-right text-ivory font-semibold tabular-nums">{fmt(invoice.amount, lang)}</td>
                  </tr>
                </tfoot>
              </table>
              </div>

              {/* Invoice actions */}
              <div className="flex items-center gap-2 mt-3 pt-3 border-t border-border">
                <button
                  onClick={() => printInvoice(invoice, client, lang)}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs text-fog hover:text-ivory transition-colors hover:bg-accent"
                >
                  <FileDown size={12} />
                  {b.actions.exportPdf}
                </button>
                {invoice.status !== 'paid' && (
                  <button
                    onClick={handlePaymentLink}
                    disabled={generatingLink}
                    className={cn(
                      'flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs transition-colors',
                      linkFeedback === 'copied'
                        ? 'text-sage bg-sage/10'
                        : linkFeedback === 'error'
                          ? 'text-ember bg-ember/10'
                          : 'text-fog hover:text-ivory hover:bg-accent'
                    )}
                  >
                    {generatingLink
                      ? <Loader2 size={12} className="animate-spin" />
                      : <Link2 size={12} />}
                    {linkFeedback === 'copied'
                      ? b.actions.paymentLinkCopied
                      : linkFeedback === 'error'
                        ? b.actions.paymentLinkError
                        : generatingLink
                          ? b.actions.generating
                          : b.actions.paymentLink}
                  </button>
                )}
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

function KpiSkeleton() {
  return (
    <div className="bg-card border border-border rounded-xl p-4 animate-pulse space-y-2">
      <Skeleton className="h-6 w-24 bg-secondary/60" />
      <Skeleton className="h-4 w-16 bg-secondary/60" />
      <Skeleton className="h-3 w-32 bg-secondary/60" />
    </div>
  );
}

function RetainerCardSkeleton() {
  return (
    <div className="rounded-xl border border-border bg-card p-4 animate-pulse space-y-4">
      <div className="flex items-start justify-between">
        <div className="space-y-2">
          <Skeleton className="h-4 w-28 bg-secondary/60" />
          <Skeleton className="h-3 w-20 bg-secondary/60" />
        </div>
        <Skeleton className="h-4 w-16 bg-secondary/60" />
      </div>
      <div className="space-y-2">
        <Skeleton className="h-2 w-full bg-secondary/60" />
      </div>
    </div>
  );
}

function InvoiceRowSkeleton() {
  return (
    <div className="rounded-xl border border-border bg-secondary/60 px-4 py-3 flex items-center gap-4 animate-pulse">
      <Skeleton className="h-4 w-24 bg-secondary/60 shrink-0" />
      <Skeleton className="h-4 w-32 bg-secondary/60 flex-1" />
      <Skeleton className="h-5 w-16 bg-secondary/60 rounded-full shrink-0" />
      <Skeleton className="h-4 w-24 bg-secondary/60 shrink-0 hidden md:block" />
      <Skeleton className="h-4 w-16 bg-secondary/60 shrink-0" />
    </div>
  );
}

import { useEffect } from 'react';
import { useSearchParams } from 'next/navigation';

export default function Billing() {
  const { t, lang } = useLang();
  const b = t.app.billing;

  const workspaces = useWorkspaces();
  const workspaceId = workspaces?.[0]?.id;

  const [page, setPage] = useState(1);
  const pageSize = 50;

  const [invoiceSheetOpen, setInvoiceSheetOpen] = useState(false);

  const searchParams = useSearchParams();
  useEffect(() => {
    if (searchParams?.get('create') === 'true' || searchParams?.get('new') === 'true') {
      setInvoiceSheetOpen(true);
    }
  }, [searchParams]);

  const { data: invoices, count: totalInvoicesCount } = useInvoices(workspaceId, page, pageSize) || { data: null, count: 0 };
  const retainers = useRetainers(workspaceId);
  const clients = useClients(workspaceId);

  const [filter, setFilter] = useState<string | 'all'>('all');
  const [query, setQuery]   = useState('');
  const [retainerSheetOpen, setRetainerSheetOpen] = useState(false);
  const [newInvoiceForm, setNewInvoiceForm] = useState({ clientId: '', description: '', amount: '', dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] });
  const [addingInvoice, setAddingInvoice] = useState(false);
  const [newRetainerForm, setNewRetainerForm] = useState({
    clientId: '',
    amount: '',
    cycle: 'monthly',
    hoursIncluded: '',
    startDate: new Date().toISOString().split('T')[0],
    notes: '',
  });

  const addRetainer = useAddRetainer();
  const addInvoice = useAddInvoice();

  async function handleAddInvoice() {
    if (!newInvoiceForm.clientId || !newInvoiceForm.amount) {
      toast.error('Please fill all required fields');
      return;
    }
    setAddingInvoice(true);
    try {
      const invoiceNumber = `INV-${new Date().getFullYear()}-${String(Math.floor(Math.random() * 9000) + 1000)}`;
      await addInvoice({
        workspaceId,
        clientId: newInvoiceForm.clientId,
        invoiceNumber,
        amount: parseFloat(newInvoiceForm.amount),
        status: 'draft',
        date: new Date().toISOString().split('T')[0],
        dueDate: newInvoiceForm.dueDate,
        items: [{ description: newInvoiceForm.description || 'Services', quantity: 1, price: parseFloat(newInvoiceForm.amount) }],
        tps: 0,
        tvq: 0,
      });
      toast.success('Invoice created.');
      setInvoiceSheetOpen(false);
      setNewInvoiceForm({ clientId: '', description: '', amount: '', dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] });
    } catch {
      toast.error('Could not create invoice.');
    } finally {
      setAddingInvoice(false);
    }
  }

  async function handleAddRetainer() {
    if (!newRetainerForm.clientId || !newRetainerForm.amount || !newRetainerForm.hoursIncluded) {
      toast.error('Please fill all required fields');
      return;
    }
    try {
      const start = new Date(newRetainerForm.startDate);
      if (newRetainerForm.cycle === 'monthly') {
        start.setMonth(start.getMonth() + 1);
      } else if (newRetainerForm.cycle === 'quarterly') {
        start.setMonth(start.getMonth() + 3);
      } else if (newRetainerForm.cycle === 'annual') {
        start.setFullYear(start.getFullYear() + 1);
      }
      const renewalDate = start.toISOString().split('T')[0];

      await addRetainer({
        workspaceId,
        clientId: newRetainerForm.clientId,
        amount: parseFloat(newRetainerForm.amount),
        cycle: newRetainerForm.cycle,
        status: 'active',
        startDate: newRetainerForm.startDate,
        renewalDate,
        hoursIncluded: parseFloat(newRetainerForm.hoursIncluded),
        hoursUsed: 0,
        notes: newRetainerForm.notes || undefined,
      });
      toast.success('Retainer added successfully');
      setRetainerSheetOpen(false);
      setNewRetainerForm({
        clientId: '',
        amount: '',
        cycle: 'monthly',
        hoursIncluded: '',
        startDate: new Date().toISOString().split('T')[0],
        notes: '',
      });
    } catch (e) {
      console.error(e);
      toast.error('Failed to create retainer');
    }
  }

  const FILTER_TABS = useMemo(() => [
    { id: 'all' as const,     label: t.app.tasks.filters.all },
    { id: 'sent' as const,    label: t.app.common.status.pending },
    { id: 'overdue' as const, label: t.app.common.status.overdue },
    { id: 'draft' as const,   label: t.app.common.status.draft },
    { id: 'paid' as const,    label: t.app.common.status.paid },
  ], [t]);

  const isLoading = invoices === null || retainers === null || clients === null;
  const outstanding = invoices ? invoices.filter((i: any) => i.status === 'sent' || i.status === 'overdue').reduce((s: any, i: any) => s + i.amount, 0) : 0;
  const paidMTD     = invoices ? invoices.filter((i: any) => i.status === 'paid').reduce((s: any, i: any) => s + i.amount, 0) : 0;
  const overdueCount = invoices ? invoices.filter((i: any) => i.status === 'overdue').length : 0;
  const activeRetainersCount = retainers ? retainers.filter((r: any) => r.status === 'active').length : 0;
  const totalPages = Math.ceil(totalInvoicesCount / pageSize);

  const visible = invoices ? invoices.filter((i: any) => {
    const matchFilter = filter === 'all' || i.status === filter;
    const matchQuery  = query === '' ||
      i.invoiceNumber.toLowerCase().includes(query.toLowerCase());
    return matchFilter && matchQuery;
  }) : [];

  return (
    <>
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
        <div>
          <TextAnimate text={b.title} type="calmInUp" className="text-2xl font-semibold text-ivory" />
          <p className="text-sm text-fog mt-0.5">
            {b.stats
              .replace('invoices', String(totalInvoicesCount))
              .replace('active retainers', String(activeRetainersCount))}
          </p>
        </div>
        <div className="flex items-center gap-2 flex-wrap">
          <Button size="sm" variant="outline" onClick={() => setRetainerSheetOpen(true)} id="btn-new-retainer">
            <Plus size={14} />
            {b.retainers.newRetainer}
          </Button>
          <Button size="sm" id="btn-new-invoice" onClick={() => setInvoiceSheetOpen(true)}>
            <Plus size={14} />
            {b.newInvoice}
          </Button>
        </div>
      </div>

      {/* Summary strip */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8">
        {isLoading ? (
          [1, 2, 3].map(i => <KpiSkeleton key={i} />)
        ) : (
          (([
            { label: b.summary.outstanding,   numericValue: outstanding,  format: (n: number) => fmt(n, lang), color: outstanding > 0 ? 'text-warm'  : 'text-sage', sub: b.summary.outstandingSub },
            { label: b.summary.overdue,       numericValue: overdueCount, color: overdueCount > 0      ? 'text-ember' : 'text-sage', sub: overdueCount > 0 ? b.summary.overdueSub : b.summary.overdueNone },
            { label: b.summary.collected,     numericValue: paidMTD,      format: (n: number) => fmt(n, lang), color: 'text-sage',   sub: b.summary.collectedSub },
          ] as Array<{ label: string; numericValue: number; format?: (n: number) => string; color: string; sub: string }>).map(s => (
            <div key={s.label} className="bg-card border border-border rounded-xl p-4">
              <p className={cn('text-2xl font-semibold tabular-nums', s.color)}>
                <AnimatedNumber value={s.numericValue} format={s.format ?? ((n) => String(Math.round(n)))} stiffness={80} damping={18} mass={0.5} />
              </p>
              <p className="text-xs text-fog mt-1">{s.label}</p>
              <p className="text-[10px] text-fog/60 mt-0.5">{s.sub}</p>
            </div>
          )))
        )}
      </div>

      {/* Retainers */}
      <section className="mb-8">
        <TextAnimate text={b.retainers.title} type="fadeIn" className="text-sm font-semibold text-ivory mb-3" />
        {isLoading ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {[1, 2, 3].map(i => <RetainerCardSkeleton key={i} />)}
          </div>
        ) : activeRetainersCount === 0 ? (
          <div className="flex flex-col items-center justify-center py-12 text-center gap-3 bg-midnight/20 rounded-xl border border-border p-6">
            <p className="text-sm text-silver font-medium">{'No retainer agreements'}</p>
            <p className="text-xs text-fog max-w-xs">{b.retainers.empty}</p>
            <Button size="sm" variant="outline" onClick={() => setRetainerSheetOpen(true)} className="rounded-full">
              <Plus size={14} className="mr-1.5" />
              {b.retainers.newRetainer}
            </Button>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {retainers?.filter((r: any) => r.status === 'active').map((ret: any) => {
              const client = clients?.find((c: any) => c._id === ret.clientId);
              const pct = ret.hoursIncluded > 0 ? Math.round((ret.hoursUsed / ret.hoursIncluded) * 100) : 0;
              const barColor = pct >= 100 ? 'var(--color-rose)' : pct >= 80 ? 'var(--color-amber)' : 'var(--color-sage)';
              return (
                <div key={ret._id} className="rounded-xl border border-border bg-card p-4">
                  <div className="flex items-start justify-between mb-3">
                    <div>
                      <p className="text-sm font-medium text-ivory">{client?.company || '...'}</p>
                      <p className="text-[10px] text-fog capitalize">
                        {ret.cycle} · {b.retainers.renews} {new Date(ret.renewalDate).toLocaleDateString(lang === 'fr' ? 'fr-FR' : 'en-GB', { day: 'numeric', month: 'short' })}
                      </p>
                    </div>
                    <p className="text-sm font-semibold text-ivory tabular-nums">{fmt(ret.amount, lang)}</p>
                  </div>
                  {/* Hours bar */}
                  <div>
                    <div className="flex justify-between text-[10px] text-fog mb-1">
                      <span>{b.retainers.hours}</span>
                      <span>{ret.hoursUsed} / {ret.hoursIncluded}h</span>
                    </div>
                    <div className="w-full h-1 rounded-full overflow-hidden bg-dusk">
                      <div
                        className="h-full rounded-full transition-all duration-500"
                        style={{ width: `${Math.min(pct, 100)}%`, backgroundColor: barColor }}
                      />
                    </div>
                  </div>
                  {ret.notes && <p className="text-[11px] text-fog/60 mt-2 leading-relaxed">{ret.notes}</p>}
                </div>
              );
            })}
          </div>
        )}
      </section>

      {/* Invoices */}
      <section>
        <div className="flex items-center gap-3 mb-4 flex-wrap">
          {/* Filters */}
          <div className="flex items-center gap-1 mb-4 overflow-x-auto">
            {FILTER_TABS.map(f => (
              <button
                key={f.id}
                onClick={() => { setFilter(f.id); setPage(1); }}
                className={cn(
                  'relative px-3 py-1 rounded-lg text-xs font-medium transition-colors shrink-0',
                  filter === f.id ? 'text-ivory' : 'text-fog hover:text-silver'
                )}
              >
                {filter === f.id && (
                  <motion.span
                    layoutId="billing-filter-pill"
                    className="absolute inset-0 rounded-lg bg-accent"
                    transition={{ type: 'spring', bounce: 0.2, duration: 0.35 }}
                  />
                )}
                <span className="relative z-10">{f.label}</span>
              </button>
            ))}
          </div>

          {/* Search */}
          <div className="relative">
            <Search size={13} className="absolute left-3 top-1/2 -translate-y-1/2 text-fog pointer-events-none" />
            <input
              type="text"
              placeholder={b.invoices.searchPlaceholder}
              value={query}
              onChange={e => setQuery(e.target.value)}
              className="pl-8 pr-3 py-1.5 rounded-lg text-xs text-foreground placeholder:text-fog outline-none transition-colors bg-secondary/60 border border-border"
            />
          </div>
        </div>

        <div className="space-y-2">
          {isLoading ? (
            <div className="space-y-2 py-4">
              {[1, 2, 3].map(i => <InvoiceRowSkeleton key={i} />)}
            </div>
          ) : visible.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-12 text-center gap-3 bg-midnight/20 rounded-xl border border-border p-6">
              <p className="text-sm text-silver font-medium">{'No invoices'}</p>
              <p className="text-xs text-fog max-w-xs">{b.invoices.empty}</p>
            </div>
          ) : (
            <>
              {visible.map((inv: any) => <InvoiceRow key={inv._id} invoice={inv} t={t} lang={lang} clients={clients} />)}
              
              {totalPages > 1 && (
                <div className="flex items-center justify-between mt-4 px-1 py-2 border-t border-border">
                  <span className="text-xs text-fog">
                    Showing {Math.min((page - 1) * pageSize + 1, totalInvoicesCount)}-{Math.min(page * pageSize, totalInvoicesCount)} of {totalInvoicesCount} invoices
                  </span>
                  <div className="flex items-center gap-2">
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => setPage(p => Math.max(p - 1, 1))}
                      disabled={page === 1}
                      className="border-border text-fog hover:text-ivory"
                    >
                      Previous
                    </Button>
                    <span className="text-xs text-silver font-medium font-mono px-2">{page} / {totalPages}</span>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => setPage(p => Math.min(p + 1, totalPages))}
                      disabled={page === totalPages}
                      className="border-border text-fog hover:text-ivory"
                    >
                      Next
                    </Button>
                  </div>
                </div>
              )}
            </>
          )}
        </div>
      </section>

      {/* Add Retainer Sheet */}
      <Sheet open={retainerSheetOpen} onOpenChange={setRetainerSheetOpen}>
        <SheetContent side="right" className="w-full sm:w-96 p-6 flex flex-col gap-6">
          <SheetHeader>
            <SheetTitle>{b.retainers.newRetainer}</SheetTitle>
          </SheetHeader>

          <div className="flex flex-col gap-4 flex-1">
            <div className="space-y-1.5">
              <Label>Client</Label>
              <Select
                value={newRetainerForm.clientId}
                onValueChange={v => setNewRetainerForm(f => ({ ...f, clientId: v }))}
              >
                <SelectTrigger>
                  <SelectValue placeholder={'Select a client'} />
                </SelectTrigger>
                <SelectContent>
                  {clients?.map((c: any) => (
                    <SelectItem key={c._id} value={c._id}>
                      {c.company}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-1.5">
              <Label>{'Amount (USD)'}</Label>
              <Input
                type="number"
                placeholder="3000"
                value={newRetainerForm.amount}
                onChange={e => setNewRetainerForm(f => ({ ...f, amount: e.target.value }))}
              />
            </div>

            <div className="space-y-1.5">
              <Label>{b.retainers.cycle}</Label>
              <Select
                value={newRetainerForm.cycle}
                onValueChange={v => setNewRetainerForm(f => ({ ...f, cycle: v }))}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="monthly">{'Monthly'}</SelectItem>
                  <SelectItem value="quarterly">{'Quarterly'}</SelectItem>
                  <SelectItem value="annual">{'Annual'}</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-1.5">
              <Label>{b.retainers.hoursIncluded}</Label>
              <Input
                type="number"
                placeholder="20"
                value={newRetainerForm.hoursIncluded}
                onChange={e => setNewRetainerForm(f => ({ ...f, hoursIncluded: e.target.value }))}
              />
            </div>

            <div className="space-y-1.5">
              <Label>{'Start Date'}</Label>
              <Input
                type="date"
                value={newRetainerForm.startDate}
                onChange={e => setNewRetainerForm(f => ({ ...f, startDate: e.target.value }))}
              />
            </div>

            <div className="space-y-1.5">
              <Label>{'Notes (optional)'}</Label>
              <Input
                placeholder="..."
                value={newRetainerForm.notes}
                onChange={e => setNewRetainerForm(f => ({ ...f, notes: e.target.value }))}
              />
            </div>
          </div>

          <Button className="w-full" onClick={handleAddRetainer}>
            {'Create Retainer'}
          </Button>
        </SheetContent>
      </Sheet>

      <Sheet open={invoiceSheetOpen} onOpenChange={setInvoiceSheetOpen}>
        <SheetContent side="right" className="w-80 bg-midnight border-l border-border">
          <SheetHeader className="pb-4 border-b border-border">
            <SheetTitle className="text-base font-semibold text-ivory">{b.newInvoice}</SheetTitle>
          </SheetHeader>
          <div className="py-5 space-y-4">
            <div className="space-y-1.5">
              <Label className="text-xs font-medium text-silver">Client *</Label>
              <Select value={newInvoiceForm.clientId} onValueChange={v => setNewInvoiceForm(f => ({ ...f, clientId: v }))}>
                <SelectTrigger className="rounded-xl bg-obsidian border-border text-ivory text-sm h-10">
                  <SelectValue placeholder={'Select client'} />
                </SelectTrigger>
                <SelectContent>
                  {(clients ?? []).map((c: any) => (
                    <SelectItem key={c._id ?? c.id} value={c._id ?? c.id}>{c.company}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs font-medium text-silver">Description</Label>
              <Input
                value={newInvoiceForm.description}
                onChange={e => setNewInvoiceForm(f => ({ ...f, description: e.target.value }))}
                placeholder={'Services rendered'}
                className="rounded-xl bg-obsidian border-border text-ivory text-sm h-10"
              />
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs font-medium text-silver">Amount (USD) *</Label>
              <Input
                type="number"
                value={newInvoiceForm.amount}
                onChange={e => setNewInvoiceForm(f => ({ ...f, amount: e.target.value }))}
                placeholder="0"
                className="rounded-xl bg-obsidian border-border text-ivory text-sm h-10"
              />
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs font-medium text-silver">Due Date</Label>
              <Input
                type="date"
                value={newInvoiceForm.dueDate}
                onChange={e => setNewInvoiceForm(f => ({ ...f, dueDate: e.target.value }))}
                className="rounded-xl bg-obsidian border-border text-ivory text-sm h-10"
              />
            </div>
          </div>
          <div className="flex gap-2 pt-2">
            <Button variant="outline" className="flex-1 rounded-xl" onClick={() => setInvoiceSheetOpen(false)}>
              {t.app.common.cancel}
            </Button>
            <Button className="flex-1 rounded-xl" onClick={handleAddInvoice} disabled={addingInvoice}>
              {addingInvoice ? <Loader2 size={14} className="animate-spin" /> : <Plus size={14} />}
              {'Create'}
            </Button>
          </div>
        </SheetContent>
      </Sheet>
    </>
  );
}

